version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala: 2.12.10

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

script: sbt -Dfile.encoding=UTF8 compilerInterface/mimaReportBinaryIssues headerCheck packageBin doc
